- id: branch-name
  name: branch name
  entry: scripts/checks.py branch-name
  language: script
  always_run: true
  pass_filenames: false

- id: commit-message
  name: commit message
  entry: scripts/checks.py commit-message
  language: script
  stages: [commit-msg]

- id: goimports
  name: goimports
  entry: scripts/checks.py goimports --fix
  language: script
  types: [go]

- id: wasm
  name: wasm
  entry: scripts/checks.py wasm
  language: script
  types: [go]
  pass_filenames: false

- id: go-vet
  name: go vet
  entry: go vet ./...
  language: system
  types: [go]
  pass_filenames: false

- id: go-build
  name: go build
  entry: go build ./...
  language: system
  types: [go]
  pass_filenames: false

- id: go-test
  name: go test
  entry: go test ./...
  language: system
  types: [go]
  pass_filenames: false

- id: verified-commits
  name: verified commits
  entry: scripts/checks.py verified-commits
  language: script
  always_run: true
  pass_filenames: false
