- id: branch-name
  name: branch name
  entry: scripts/checks.py branch-name
  language: script
  always_run: true
  pass_filenames: false

- id: commit-message
  name: commit message
  entry: scripts/checks.py commit-message
  language: script
  stages: [commit-msg]

- id: goimports
  name: goimports
  entry: scripts/checks.py goimports --fix
  language: script
  types: [go]

- id: wasm
  name: wasm
  entry: scripts/checks.py wasm
  language: script
  types: [go]
  pass_filenames: false

- id: go-fix
  name: go fix
  entry: go fix ./...
  language: system
  types: [go]
  pass_filenames: false

- id: go-vet
  name: go vet
  entry: go vet ./...
  language: system
  types: [go]
  pass_filenames: false

- id: golangci-lint
  name: golangci-lint
  entry: scripts/checks.py golangci-lint
  language: script
  types: [go]
  pass_filenames: false

- id: go-build
  name: go build
  entry: go build ./...
  language: system
  types: [go]
  pass_filenames: false

- id: go-test
  name: go test
  entry: go test ./...
  language: system
  types: [go]
  pass_filenames: false

- id: govulncheck
  name: govulncheck
  entry: govulncheck
  language: golang
  args: ["./..."]
  additional_dependencies:
    - golang.org/x/vuln/cmd/govulncheck@v1.1.4
  files: (^go\.mod$|^go\.sum$|\.go$)
  pass_filenames: false

- id: gendocs
  name: gendocs
  entry: bash -c 'go generate ./... && git diff --exit-code README.md'
  language: system
  files: (^cmd/certkit/.*\.go$|^README\.md$|^doc\.go$)
  pass_filenames: false

- id: go-mod-update
  name: go mod update
  entry: bash -c 'go get -u ./... && go mod tidy'
  language: system
  files: \.go$
  pass_filenames: false
  stages: [manual]

- id: npm-update
  name: npm update
  entry: bash -c 'cd web && npm update'
  language: system
  files: ^web/
  pass_filenames: false
  stages: [manual]

- id: prettier
  name: prettier
  entry: prettier --write
  language: node
  additional_dependencies:
    - prettier@latest
  types_or: [javascript, ts, css, html]
  exclude: wasm_exec\.js$

- id: vitest
  name: vitest
  entry: bash -c 'cd web && vitest run'
  language: node
  additional_dependencies:
    - vitest@^3.0.0
    - jsdom@^26.0.0
  files: ^web/
  exclude: wasm_exec\.js$
  pass_filenames: false

- id: wrangler-build
  name: wrangler build
  entry: bash -c 'cd web && wrangler pages functions build --outdir /tmp/certkit-fn-check'
  language: node
  additional_dependencies:
    - wrangler@latest
  files: ^web/functions/
  types: [ts]
  pass_filenames: false

- id: verified-commits
  name: verified commits
  entry: scripts/checks.py verified-commits
  language: script
  always_run: true
  pass_filenames: false
