- id: branch-name
  name: branch name
  entry: python3 scripts/checks.py branch-name
  language: python
  always_run: true
  pass_filenames: false

- id: commit-message
  name: commit message
  entry: python3 scripts/checks.py commit-message
  language: python
  stages: [commit-msg]

- id: goimports
  name: goimports
  entry: python3 scripts/checks.py goimports --fix
  language: python
  types: [go]

- id: verified-commits
  name: verified commits
  entry: python3 scripts/checks.py verified-commits
  language: python
  always_run: true
  pass_filenames: false
